### ISSUE TITLE
Optional List routes after a scan

### ISSUE THREAD

**Issue by mrsimonbennett** [LaravelCollective/annotations#1]
Hello,

I proposed this when it was still in the core, Wonder what you think.

https://github.com/laravel/framework/pull/6481

**Comment by adamgoose** [comment]
Go ahead and send another PR to this repo.

**Comment by mrsimonbennett** [comment]
(Y)

**Comment by mrsimonbennett** [comment]
:thumbsup:

see https://github.com/LaravelCollective/annotations/pull/2
