### ISSUE TITLE
[Proposal] Route Model Binding

### ISSUE THREAD

**Issue by adamgoose** [LaravelCollective/annotations#10]
So here's the idea... When you register a resource controller with the `@Resource` annotation, I think it'd be nice to be able to specify the model that the resource is for. For example...

``` php
/**
 * @Resource("users", model="App\User")
 */
class UsersController extends Controller {
    // Resource Controller Methods
}
```

This would register routes in the following fashion:

``` php
  $route->resource('users', [{Users Controller Definition}]);

  $route->model('users', 'App\User');
```

Please share your thoughts and help me determine if...
1. This is a good place to put such an annotation.
2. It'd even be helpful to anyone.

Thanks,
Adam.

**Comment by tshafer** [comment]
I think this is a great idea. It is a route after all.

**Comment by thecotne** [comment]
what will be replacement for this?

``` php
Route::bind('user', function($username)
{
    $user = App\User::where('username', $username)->first();
    if ($user) {
        return $user;
    } else {
        throw new NotFoundHttpException;
    }
});
```

**Comment by tshafer** [comment]
Good question. This is something that still needs to be hashed out. Any ideas?

**Comment by thecotne** [comment]
``` php
/**
 * @Resource("users", model="App\User", modelBindBy="username")
 */
class UsersController extends Controller {
    // Resource Controller Methods
}
```

or

``` php
/**
 * @Resource("users", model="App\User", modelBindMethod="some_controler_method")
 */
class UsersController extends Controller {
    // Resource Controller Methods
    protected function some_controler_method($username)
    {
        $user = App\User::where('username', $username)->first();
        if ($user) {
            return $user;
        } else {
            throw new NotFoundHttpException;
        }
    }
}
```

**Comment by RobinMalfait** [comment]
@thecotne you can actually replace this with a shorter syntax, so maybe easier to fix?

``` php
Route::bind('user', function($username)
{
    return App\User::where('username', $username)->firstOrFail();
});
```

**Comment by dwightwatson** [comment]
You might also need to consider what happens when it's a nested resource and you want to use model binding. For example, the nested model in a resource probably needs to be confirmed that it belongs to the parent resource.

There has been some discussion on this problem in laravel/framework#7132. Hopefully the framework can provide a good solution to this problem and then an appropriate implementation can be perfected in the annotations.

**Comment by adamgoose** [comment]
I've switched this proposal to be something along these lines:

``` php
/**
 * @Bind("users")
 */
class User extends Eloquent {
  //
}
```

This annotation is currently featured in the master branch.

**Comment by RobinMalfait** [comment]
@adamgoose Can annotations work as an interface?

Like if you could say that when you have a `@BindModel` that you have to implement a method in that model like 

``` php
/**
 * @Bind("username")
 */
class User extends Eloquent {
  public function bindModel($param) // username
  {
    return $this->where('username', '=', $param)->first();
  }
}
```

And if you use routes you have this:
`get("/users/{username}", "UsersController@show");`

If you use it this way, you are not limited to `User::find($x);`

**Comment by adamgoose** [comment]
Yeah, I like this idea. Can you please submit it as another Issue? We can implement it in the next release.

**Comment by dwightwatson** [comment]
Laravel 5 introduced the concept of a [route key for Eloquent models](http://laravel.com/docs/5.0/eloquent#model-url-generation). The [`UrlRoutable` interface](https://github.com/laravel/framework/blob/5.0/src/Illuminate/Contracts/Routing/UrlRoutable.php) could make the default lookup smarter.

`$model->where($model->getRouteKeyName(), $param)->firstOrFail();`
