### ISSUE TITLE
Route Model Binding Idea

### ISSUE THREAD

**Issue by RobinMalfait** [LaravelCollective/annotations#13]
Hey!

Can annotations work as an interface?

Like if you could say that when you have a `@BindModel` that you have to implement a method in that model like 

``` php
/**
 * @Bind("username")
 */
class User extends Eloquent {

  public function bindModel($param) // username
  {
    return $this->where('username', '=', $param)->first();
  }

}
```

And if you use routes you have this:

``` php
get("/users/{username}", "UsersController@show");
```

If you use it this way, you are not limited to 

``` php
User::find($x);
```

What do you guys think? :)

**Comment by adamgoose** [comment]
Look at this...

https://github.com/laravel/framework/blob/5.0/src/Illuminate/Routing/Router.php#L938-L959
