### ISSUE TITLE
Using literal quotes breaks the package

### ISSUE THREAD

**Issue by kirkbushell** [LaravelCollective/annotations#14]
If I do the following:

``` php
/**
 * @Middleware('shift.account')
 */
class RegistrationController extends Controller
{
```

It results in the following error:

```
[Syntax Error] Expected PlainValue, got ''' at position 12 in class AwardForce\Http\Controllers\RegistrationController.
```

This is easily solved by using double quotes ("") however - this was not clear at all initially. Both single and double quotes should be supported. In fact, because there are no variables - single quotes should even be the default (to match the language).

**Comment by adamgoose** [comment]
As much as I agree with you, this is the responsibility of the Doctrine Annotations package. Laravel Annotations simply uses the Doctrine package to read the annotations, and register the routes accordingly. Unfortunately, we do not control how the annotations are interpreted.
