### ISSUE TITLE
Minor issue - convert the project to proper FIG standards

### ISSUE THREAD

**Issue by kirkbushell** [LaravelCollective/annotations#17]
It's a big public project - help support the standards that are in place, rather than using Laravel's bastardised version ;)

**Comment by tshafer** [comment]
We support pull requests.

**Comment by Anahkiasen** [comment]
:+1:

**Comment by adamgoose** [comment]
Thanks for your feedback, guys. But we're going to stick with the Laravel code style until Laravel switches to PSR-2 in just a couple of weeks with the release of 5.1. Thanks.
