### ISSUE TITLE
Model bindings not being read when routes are cached

### ISSUE THREAD

**Issue by Anahkiasen** [LaravelCollective/annotations#19]
I don't know if this is a bug or a peculiarity of behavior not explained in the docs, but when routes are cached, the scanned model bindings are not being loaded, because of [this condition](https://github.com/LaravelCollective/annotations/blob/master/src/AnnotationsServiceProvider.php#L122)

Should the model bindings be cached too or something?

**Comment by adamgoose** [comment]
No, you're right. That's a bug. Would you mind submitting a PR that removes that `if` statement?
