### ISSUE TITLE
Route model binding is ignored in one controller

### ISSUE THREAD

**Issue by hackel** [LaravelCollective/annotations#24]
This is a really odd issue.  I've defined a binding in my model.  On my local installation, this works perfectly for both my admin and api controllers.  I've just deployed this project to a dev server, and the binding works fine on the api routes, but is ignored on the admin routes.  A plain ID string is being passed into my controller methods instead of the respective model.  I cannot account for this.

The code is the same and I've cleared every cache I can find.  What could be causing this discrepancy?  Both the working (api) and non-working (admin) controllers are defined in exactly the same way, and using the same model binding.  If I add the binding manually in my RouteServiceProvider, it again works just fine.

I've had no luck debugging this myself.  Appreciate any insights!

**Comment by adamgoose** [comment]
Can you please share two files:
- `storage/app/models.scanned.php`
- `storage/app/routes.scanned.php`

Also, could you please truncate the `routes.scanned.php` to include ONLY the relevant routes. Essentially, I'd like _all_ of the routes for _one_ API controller, and for _one_ Admin controller.

**Comment by hackel** [comment]
Bah, I finally figured out the issue.  I simply needed to run "artisan model:scan" to generate my models.scanned.php file.  I never had to do this on my local instance, presumably because I have set `$scanWhenLocal = true`.  This should really be added to the documentation!
