### ISSUE TITLE
Add @Composes annotation

### ISSUE THREAD

**Issue by Anahkiasen** [LaravelCollective/annotations#25]
For view composers:

``` php
/**
 * @Composes("some/view")
 */
class MyComposer
{
  public function compose(View $view)
  {
    // ...
  }
}

class AdminComposer
{
  /**
   * @Composes({"admin/foo", "admin/bar"})
   */
  public function composeFoo(View $view)
  {
    // ...
  }

  /**
   * @Composes("bar")
   */
  public function composeBar(View $view)
  {
    // ...
  }
}
```

Would be nice in my opinion, what do you think?

**Comment by Anahkiasen** [comment]
I have this working [in a fork](https://github.com/LaravelCollective/annotations/compare/5.0...Anahkiasen:feature/composer-annotations?expand=1) but as you can see every time a scanner type is added there is a _load_ of boilerplate that is repeated all across the codebase. 

Shouldn't most of that be abstracted somewhere? Seems to be pretty much always the same thing (register the scanner, check if file exists, scan in local if needed, etc etc)

**Comment by tshafer** [comment]
I'll talk to Adam and see if he's open to adding this functionality.

**Comment by Anahkiasen** [comment]
Any news on this one?
