### ISSUE TITLE
Add ability to specify method for @Bind

### ISSUE THREAD

**Issue by Anahkiasen** [LaravelCollective/annotations#26]
Example:

``` php
/**
 * @Bind("user", with="findBySlug")
 */
class User extends Model
{
  // ...
}
```

Translating to

``` php
$router->bind('user', 'User@findBySlug')
```

Currently if you don't use the default `find` method, you can't use the annotation.

**Comment by tshafer** [comment]
Correct, you would need bind your model with a closure to do this.  There was discussion about adding something like this but it was decided to keep it simple.

**Comment by Anahkiasen** [comment]
> Correct, you would need bind your model with a closure to do this

What do you mean? The @ syntax works for route bindings too, in my example there would be a findBySlug method on the model

**Comment by hackel** [comment]
+1 This would be very useful.

**Comment by hackel** [comment]
@tshafer Any update on this?  You very rudely closed my PR without giving any comment or indication as to why it was unacceptable and ignored my request for more information.  Let's work to find a reasonable solution to this so that I do not have to continue to maintain a separate fork.
