### ISSUE TITLE
Defining parent method disables annotated routes

### ISSUE THREAD

**Issue by hackel** [LaravelCollective/annotations#29]
All of my controllers extend an abstract base controller.  If I define an update() method in that base controller, route annotations stop working on all controllers that extend from that base.  I'm using @resource controllers.  There are no route annotations at all in the base controller.  If I try to add a route annotation (e.g. @get) to the update() method in the base controller, the route does show up, and picks my last (alphabetically) child controller's update method as the action.  

If I change the name of the update method in my parent controller, everything works fine, so I will do that for now as a temporary work-around.

**Comment by tshafer** [comment]
We accept pull requests.
