### ISSUE TITLE
Laravel 5.1 support?

### ISSUE THREAD

**Issue by Anahkiasen** [LaravelCollective/annotations#32]
I see `laravelcollective/html` is already supporting 5.1 but annotations is not, is there a major blocking point preventing support currently?

**Comment by adamgoose** [comment]
Sorry, no. Just haven't had time to branch-alias it. I plan to work on getting things ready for Tuesday this weekend.

**Comment by Anahkiasen** [comment]
Aight cool, good to know, thanks!

**Comment by jonathanpmartins** [comment]
Will know when come ou too! :+1:

**Comment by jonathanpmartins** [comment]
@adamgoose @tedslittlerobot @tshafer @Anahkiasen 

Just change the composer.json files to support symfony console 2.7 and symfony finder 2.7.

```
"require": {
    "php": ">=5.4.0",
    "illuminate/console": "~5.0",
    "illuminate/filesystem": "~5.0",
    "illuminate/support": "~5.0",
    "doctrine/annotations": "~1.0",
    "symfony/console": "2.7.*",
    "symfony/finder": "2.7.*"
},
```

I tried it out with composer, take a look:

https://github.com/jonathanpmartins/annotations-laravel-5-1 
https://packagist.org/packages/jonathanpmartins/annotations-for-laravel-5.1#5.0.x-dev

....in my composer.json:

"jonathanpmartins/annotations-for-laravel-5.1": "5.0.*@dev",

Installation of new L5.1 done. Annotations working fine, until now... heehehehe

**Comment by jonathanpmartins** [comment]
L5.1 lauched!

**Comment by bkintanar** [comment]
Still no updates on this yet?

**Comment by jonathanpmartins** [comment]
@adamgoose @tshafer Can you create the new annotation 5.1 branch? So we can propose a Pull Request?

**Comment by jonathanpmartins** [comment]
@adamgoose Nice! Thank you very Much! :smile:
