### ISSUE TITLE
Limit the scanEverything method

### ISSUE THREAD

**Issue by IonutBajescu** [LaravelCollective/annotations#35]
I think that we should have an option to scan only certain namespaces. (like App\Models, App\Http\Controllers - you get the idea)

In the current state,  $scanEverything takes 4 seconds of the booting load which is enormous and makes the development impossible.

If no one has something against this feature I'll do a pull request as soon as possible.

**Comment by tshafer** [comment]
I ran into this problem last night. I like the idea.
