### ISSUE TITLE
@Middleware not inherited from parent class

### ISSUE THREAD

**Issue by chasen** [LaravelCollective/annotations#36]
If you are using a base class to accomplish route "groups" for middle ware the annotation isnt inherited

```
<?php
namespace App\Http\Controllers;
/**
 * @Middleware("auth")
 */
class BaseController
{
    ...
}


<?php
namespace App\Http\Controllers;

class SomeController extends BaseController
{
    /**
     * @Get("/some-path")
     */
    public function index()
    {
        ....
    }
}
```

Running `php artisan route:scan` completes without errors but `php artisan route:list` shows the route without the middleware.

Is this working as intended or a bug?

**Comment by adamgoose** [comment]
At the moment, it is "as expected," however it would be possible for us to scan class inheritance for annotations and apply them as well. Will keep this issue open as a Feature Request.

**Comment by takahashiyuya** [comment]
Also `@Controller` prefix is not inherited from parent.

**Comment by tshafer** [comment]
We accept pull requests.
