### ISSUE TITLE
Add `vendor:publish` capability to install a stubbed ServiceProvider

### ISSUE THREAD

**Issue by adamgoose** [LaravelCollective/annotations#4]
Using the `$this->publishes()` method, documented [here](http://laravel.com/docs/5.0/packages), let's give the ability for users to install the proper `AnnotationsServiceProvider` directly into their `base_path('app/Providers')` directory.

**Comment by tshafer** [comment]
+1

**Comment by StefanPrintezis** [comment]
Why was this closed? I'm asking because I want to implement this behaviour in my package.
