### ISSUE TITLE
How can I auto define routenames for Controllers like resources done

### ISSUE THREAD

**Issue by tifidy** [LaravelCollective/annotations#41]
Question is simple Is there a way to do that with annotations?

I need {prefix}.{@Get("url")}.controllerMethod how can I automize that?

**Comment by Anahkiasen** [comment]
`@Controller(prefix="foobar")` on the class itself works for me

**Comment by Younesi** [comment]
`@Controller("bars", prefix="foo")` creates routes for example  like `foo/bars/create` but the route name is still without prefix! it's `bars.create`
