### ISSUE TITLE
Implement web and auth middleware globally

### ISSUE THREAD

**Issue by EmilMoe** [LaravelCollective/annotations#46]
Following https://github.com/LaravelCollective/annotations/issues/44

Is there a way to globally add these to all routes? I tried in Controller.php but that didn't work. I would like not have to write it in top of all my controllers.

**Comment by Grummfy** [comment]
perhaps #57 can help on this?

**Comment by bl0wfish** [comment]
A solution would be to override the _loadScannedRoutes_ method in your _AnnotationsServiceProvider_ like this:

```
protected function loadScannedRoutes()
{
    $this->app->booted(function () {
        $router = $this->app['Illuminate\Contracts\Routing\Registrar'];

        $router->group(['middleware' => 'web'], function() use($router) {
            require $this->finder->getScannedRoutesPath();
        });
    });
}
```

**Comment by tshafer** [comment]
We accept pull requests.
