### ISSUE TITLE
ClassFinder.php removed in laravel 5.4

### ISSUE THREAD

**Issue by bastian-schur** [LaravelCollective/annotations#55]
In Laravel 5.4 the Illuminate\Filesystem\ClassFinder.php was removed.

Annotations use this class and nothing works!

> Class Illuminate\Filesystem\ClassFinder does not exist

**Comment by mlantz** [comment]
Turns out it was missed because the class was actually mocked in the tests, I've brought the file from 5.3 forward into the codebase, so I'll review and release later today, sorry about this.
