### ISSUE TITLE
[features]Route scanning inside route definition

### ISSUE THREAD

**Issue by Grummfy** [LaravelCollective/annotations#57]
Hello,

So grouping with annotation is something that's missing.

1) So I got a first idea. In a route file, declaring something like this :

```php
Route::group(['prefix' => 'foo'], function ()
{
  Route::scan(app_path('Http/Controllers/Foo'));
});
```
So, it will scan the Foo directory and all route given by the annotation will inherit of group property (middleware, prefix, etc). So if we find a method or a controller with a prefix, it will be added, etc.
So, for sure we will require to cache this to avoid losing a lot of time...

:+1: All route are "defined" in same place. 
:-1: Can make really slow system if many stuff to scan

2) Another way of doing it, could be, grouping Controller of a group inside a directory, and all annotated controller of this directory will got some properties.  So inside the AnnotationsServiceProvider we should get something like

```php
	protected $scanRoutesGroupsByDirectory = [
		'Foo' => ['prefix' => 'foo', 'midleware' => ['auth', 'another-middleware']],
	];
```

:+1: Work in the same way as now
:-1: Route are define in two spot

3) Create a toScan.php file inside the routes directory with a structure like this
```php
return [
	'*' => [ // on all annotated controller & method, add these properties
		'middleware' => ['auth', 'trim'],
	],
	'Foo' => [ // on annotated controller & method inside the directory Foo add these properties
		'prefix' => 'foo'
	]
	'Bar', // scan Bar directory
	'BazController.php' // scan these controller
];
```

:+1: All route are define inside one directory, we keep the scan command to have theses routes

So what do you think about theses ideas?

**Comment by tshafer** [comment]
We accept pull requests.
