### ISSUE TITLE
abandonned ?

### ISSUE THREAD

**Issue by Grummfy** [LaravelCollective/annotations#61]
Hello,
is this project abandoned?

**Comment by mvatansever** [comment]
Does anyone may answer this question?

**Comment by mvatansever** [comment]
I use my own fixed version for a 5 month and I didn't face any problem until now. 
If you want to use this package add below codes to your **composer.json** :
`	"require": {
		"laravelcollective/annotations-edited": "dev-master",
	},
	"repositories": [
		{
			"type": "git",
			"url": "https://github.com/mvatansever/annotations"
		}
	]`

Or you should download the package from my repository and use it wherever you want to store.

**Comment by mohammedzaki** [comment]
ok, Thanks a lot,
I will work on it.

**Comment by Grummfy** [comment]
At least the author should declare it abandoned and let someone take the relay on it.

ping @adamgoose or @tshafer ?

**Comment by tshafer** [comment]
No abandoned. I will try to run through all of the packages daily.
