### ISSUE TITLE
Laravel 5.5

### ISSUE THREAD

**Issue by professor93** [LaravelCollective/annotations#68]
Can i use with Laravel 5.5?

**Comment by montyclt** [comment]
https://github.com/LaravelCollective/annotations/issues/65

**Comment by mohammedzaki** [comment]
you can use it at this repo https://github.com/mohammedzaki/annotations.git
on composer file
add this version to require-dev section
"require-dev": {
"laravelcollective/annotations": "5.5.0"
}
and add this repo to repositories section
"repositories": [
        {
            "type": "git",
            "url": "https://github.com/mohammedzaki/annotations.git"
        }
    ]

**Comment by alexf-edp** [comment]
Tried the above repo https://github.com/mohammedzaki/annotations.git; v5.5.0 seem like it is not fully compatible with Laravel 5.5; some of the console commands have fire() methods in them.
Such as the  RouteScanCommand.php, EventScanCommand.php and ModelScanCommand classes. @

**Comment by igronus** [comment]
Just write `"laravelcollective/annotations": "5.*"` to your require section of composer.json and do update.
