### ISSUE TITLE
laravel 5.6?

### ISSUE THREAD

**Issue by Grummfy** [LaravelCollective/annotations#73]
IS it compatible with 5.6?

**Comment by lucasctd** [comment]
I tried to install it on a Laravel 5.6 project and it does not work.
Laravel 5.6 requires illuminate/filesystem: v5.6.3 but laravelcollective/annotations (dev-master / 5.5.x-dev) requires illuminate/filesystem: 5.5.*.

**Comment by tshafer** [comment]
Ill get this upgraded to 5.6 tonight.

**Comment by vesper8** [comment]
@tshafer any update please? I love this package and use it everywhere!

**Comment by EmilMoe** [comment]
Yeah.. I would like an update too

**Comment by tshafer** [comment]
Sorry. I got swamped. I'll tackle this in the morning.

**Comment by EmilMoe** [comment]
Still no updates?

**Comment by tshafer** [comment]
Its there.
