### ISSUE TITLE
Laravel Annotation commands

### ISSUE THREAD

**Issue by lukasvy** [LaravelCollective/annotations#75]
function fire of commands EventScanCommand.php, ModelScanCommand.php, RouteScanCommand.php should be renamed to handle

**Comment by johntimothybailey** [comment]
@lukasvy *You may have already noticed* the commands have `handle` instead of `fire` starting with version [`5.5`](https://github.com/LaravelCollective/annotations/blob/5.5/src/Console/ModelScanCommand.php#L59)

The default branch is `5.6` and it is the latest available on packagist

**Comment by loonytoons** [comment]
Closing as the function is already called `handle` in the latest versions, thanks @johntimothybailey
