### ISSUE TITLE
[Idea] event:list

### ISSUE THREAD

**Issue by mrsimonbennett** [LaravelCollective/annotations#9]
What do you think to the idea of listing all events in a CLI table.

**Comment by RobinMalfait** [comment]
Actually, I would love this!

**Comment by mrsimonbennett** [comment]
eg

![screen shot 2015-02-26 at 21 58 01](https://cloud.githubusercontent.com/assets/1471305/6402822/92effd1a-be02-11e4-8c80-101c772f449e.png)

**Comment by RobinMalfait** [comment]
@adamgoose do you like this? :)

**Comment by RobinMalfait** [comment]
@mrsimonbennett I like that actually :+1:

**Comment by tshafer** [comment]
This is a request for the laravel core.
