### ISSUE TITLE
Laravel 6 ErrorException  : Undefined property: Collective\Annotations\Routing\Annotations\ResourcePath::$no_prefix

### ISSUE THREAD

**Issue by tjhunkin** [LaravelCollective/annotations#94]
PHP 7.2.19
Laravel Framework 6.16.0
laravelcollective/annotations v6.0.2

config/app.php 

When including the provider: App\Providers\AnnotationsServiceProvider::class

I get the following error:

**ErrorException  : Undefined property: Collective\Annotations\Routing\Annotations\ResourcePath::$no_prefix**

**Comment by tjhunkin** [comment]
@Controller needs to appear BEFORE @Resource

E.g. 
 * @Controller(prefix="tickets")
 * @Resource("ticket", only={"store"})

**Comment by loonytoons** [comment]
thanks @tjhunkin. I'll take a look into it as soon as I can, see if it's possible to remove that constraint, but will update the docs if nothing else

**Comment by tjhunkin** [comment]
Thanks @loonytoons
