### ISSUE TITLE
Laravel 7 compatibility

### ISSUE THREAD

**Issue by vesper8** [LaravelCollective/annotations#95]
`6.0` is not compatible with Laravel 7 due to `illuminate/filesystem ^6.0`

@mlantz Any chance you could release a new version with Laravel 7 compatibility like you did 5 months ago for Laravel 6? 

That would be great!!! Thanks!

**Comment by vesper8** [comment]
@mlantz or @loonytoons or @alexfoo any chance one of you could please merge https://github.com/LaravelCollective/annotations/pull/96/files and tag a new 7.0 release pretty please?

many thanks

**Comment by loonytoons** [comment]
👍 thanks for the prompt. I won't have time to look today unfortunately, but after that will see if I can get those tests passing so we can get that merged (unless anyone beats me to it)

**Comment by loonytoons** [comment]
Sorry for the delay, I've updated that branch to fix the tests and created a 7.0 release.
Shout out if there are any issues, I only have a very basic setup to test against at the moment

**Comment by vesper8** [comment]
thank you @loonytoons !
