### ISSUE TITLE
When are you going to support Laravel 8?

### ISSUE THREAD

**Issue by kw-jeff** [LaravelCollective/annotations#99]
Hello.

My Project created using laravel 8.

So I want to use annotations but not support for laravel 8.

I need help

Thank you.

**Comment by loonytoons** [comment]
Thanks @kw-jeff, this should be coming in the next few days, sorry for the delay!

**Comment by loonytoons** [comment]
@kw-jeff I've just pushed the laravel 8 compatible release. Let me know if you have any issues!
